### ISSUE TITLE
Implementation of Product Preview

### ISSUE THREAD

**Issue by turbo-ele** [sulu/SuluProductBundle#344]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

When editing a product all changes should be seen in a live preview.

**Todo's**
* [ ] Only show preview, when content administration is enabled.
* [ ] Show the default template in preview.
* [ ] Show selected template, once product templating is implemented.
